-- DDL Schema for Credit Risk Relational Database

-- Primary Applications Table
CREATE TABLE IF NOT EXISTS applications (
    SK_ID_CURR INTEGER PRIMARY KEY,
    TARGET INTEGER,
    NAME_CONTRACT_TYPE VARCHAR(50),
    CODE_GENDER CHAR(1),
    FLAG_OWN_CAR CHAR(1),
    FLAG_OWN_REALTY CHAR(1),
    CNT_CHILDREN INTEGER,
    AMT_INCOME_TOTAL REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_TYPE_SUITE VARCHAR(50),
    NAME_INCOME_TYPE VARCHAR(100),
    NAME_EDUCATION_TYPE VARCHAR(100),
    NAME_FAMILY_STATUS VARCHAR(100),
    NAME_HOUSING_TYPE VARCHAR(100),
    REGION_POPULATION_RELATIVE REAL,
    DAYS_BIRTH INTEGER,
    DAYS_EMPLOYED INTEGER,
    DAYS_REGISTRATION REAL,
    DAYS_ID_PUBLISH INTEGER,
    OWN_CAR_AGE REAL,
    FLAG_MOBIL INTEGER,
    FLAG_EMP_PHONE INTEGER,
    FLAG_WORK_PHONE INTEGER,
    FLAG_CONT_MOBILE INTEGER,
    FLAG_PHONE INTEGER,
    FLAG_EMAIL INTEGER,
    OCCUPATION_TYPE VARCHAR(100),
    CNT_FAM_MEMBERS REAL,
    REGION_RATING_CLIENT INTEGER,
    REGION_RATING_CLIENT_W_CITY INTEGER,
    EXT_SOURCE_1 REAL,
    EXT_SOURCE_2 REAL,
    EXT_SOURCE_3 REAL
);

-- Credit Bureau Historical Records
CREATE TABLE IF NOT EXISTS bureau (
    SK_ID_BUREAU INTEGER PRIMARY KEY,
    SK_ID_CURR INTEGER,
    CREDIT_ACTIVE VARCHAR(50),
    CREDIT_CURRENCY VARCHAR(50),
    DAYS_CREDIT INTEGER,
    CREDIT_DAY_OVERDUE INTEGER,
    DAYS_CREDIT_ENDDATE INTEGER,
    DAYS_ENDDATE_FACT INTEGER,
    AMT_CREDIT_MAX_OVERDUE REAL,
    CNT_CREDIT_PROLONG INTEGER,
    AMT_CREDIT_SUM REAL,
    AMT_CREDIT_SUM_DEBT REAL,
    AMT_CREDIT_SUM_LIMIT REAL,
    AMT_CREDIT_SUM_OVERDUE REAL,
    CREDIT_TYPE VARCHAR(100),
    DAYS_CREDIT_UPDATE INTEGER,
    AMT_ANNUITY REAL,
    FOREIGN KEY(SK_ID_CURR) REFERENCES applications(SK_ID_CURR)
);

-- Installment Payments History
CREATE TABLE IF NOT EXISTS installments_payments (
    SK_ID_PREV INTEGER,
    SK_ID_CURR INTEGER,
    NUM_INSTALMENT_VERSION REAL,
    NUM_INSTALMENT_NUMBER INTEGER,
    DAYS_INSTALMENT REAL,
    DAYS_ENTRY_PAYMENT REAL,
    AMT_INSTALMENT REAL,
    AMT_PAYMENT REAL,
    FOREIGN KEY(SK_ID_CURR) REFERENCES applications(SK_ID_CURR)
);

-- Indexing for Query Optimization
CREATE INDEX IF NOT EXISTS idx_applications_target ON applications(TARGET);
CREATE INDEX IF NOT EXISTS idx_bureau_curr ON bureau(SK_ID_CURR);
CREATE INDEX IF NOT EXISTS idx_installments_curr ON installments_payments(SK_ID_CURR);
